kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense-tracker
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30081
