kind: ConfigMap
apiVersion: v1
metadata:
  name: backend-config
  namespace: expense-tracker
data:
  PGUSER: postgres
  PGPASSWORD: password
  PGDATABASE: expensetracker
  PGHOST: postgres
  PGPORT: "5432"
