kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: expense-tracker
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
